added protection to views if not logged in, put login screens on cent…
onocy/doma pull request #69
Opened 2017-12-01 05:55 UTC by onocy

…ered card, added main redirect towards login

2017-12-04 01:30 UTC, mboneil10 reviewed
I'm confused, isn't this 'login_required' business the same thing that you're doing in the other PR you have open?

2017-12-05 06:18 UTC, L4r1k requested changes
Definitely good to secure the views like this. Just a few comments left but looks good other than those

2017-12-05 06:18 UTC, Cobchise commented on cleanslate/cleanslate/urls.py
> +    url(r'^$', auth_views.login, name='doma-login'),
Why is this and line 22 necessary?

2017-12-05 06:18 UTC, Cobchise commented on cleanslate/cleanslate/urls.py
> -    url(r'^$', home, name='doma/login/'),
Removing this breaks the 'home' button (the doma button in the center of the navbar). It now asks for a login on every press and upon logging in just redirects to the profile page.

2017-12-05 15:46 UTC, merged